name:                haas
version:             0.1.0.0
github:              "githubuser/haas"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haas#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haas-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haas
    - bytestring
    - vector
    - containers
    - reflection
    - array
    - extra
    - fgl
    - hashmap
    - heaps
    - lens
    - mwc-random
    - psqueues
    - unboxing-vector
    - unordered-containers
    - utility-ht
    - vector-algorithms
    - QuickCheck
    - attoparsec
    - deepseq
    - hashable
    - mtl
    - parallel
    - parsec
    - primitive
    - random
    - template-haskell
    - text
    - tf-random
    - transformers
    - split
    - aeson
    - http-conduit
    - lens-aeson
    - http-types
    - text-regex-replace
    - regex-posix

tests:
  haas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haas
